/// <reference types="cypress" />

it("Add a new contact", async () => {
  const users = await cy.fixture("users")
  cy.visit("/")
  cy.get("#add-new-contact").click()
  cy.url().should("include", "/new-contact")

  cy.get("h2").contains("Add a new contact")
  cy.get("#first-name")
    .type(users[0].firstName)
    .should("have.value", users[0].firstName)
  cy.get("#last-name")
    .type(users[0].lastName)
    .should("have.value", users[0].lastName)
  cy.get("#phone-number")
    .type(users[0].phoneNumber)
    .should("have.value", users[0].phoneNumber)
  cy.get("#submit").click()

  cy.get("table#contact-list").should("exist")
  cy.get("table#contact-list")
    .contains("td", users[0].firstName)
    .should("be.visible")
  cy.get("table#contact-list")
    .contains("td", users[0].lastName)
    .should("be.visible")
  cy.get("table#contact-list")
    .contains("td", users[0].phoneNumber)
    .should("be.visible")
})
