import Head from "next/head"
import Link from "next/link"
import { useRouter } from "next/router"
import Modal from "react-modal"
import ContactsList from "../components/ContactsList"
import NewContactModal from "../components/NewContactModal"

Modal.setAppElement("#__next")

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Modal
        isOpen={!!router.query["new-contact"]}
        onRequestClose={() => router.push("/")}
        contentLabel="Post modal"
        overlayClassName="fixed inset-0 flex justify-center bg-gray-900/75"
        className="w-full max-w-screen-md p-5 border md:my-10 border-gray-200 shadow bg-white rounded-lg"
      >
        <NewContactModal />
      </Modal>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex justify-between p-4 header-border">
        <h1 className="text-2xl font-bold text-gray-800">Phone Book</h1>
        <Link href="/?new-contact=true" as="/new-contact" passHref>
          <a className="bg-gray-100 text-gray-800 font-semibold py-1 px-2 rounded-sm">
            Add a new contact
          </a>
        </Link>
      </header>

      <main className="w-full max-w-screen-xl mx-auto">
        <div className="p-3">
          <input
            className="w-full h-full mt-2 p-3 bg-gray-100 text-base rounded-md border-gray-300"
            type="text"
            placeholder="Search by"
          />
          <ContactsList />
        </div>
      </main>

      <footer className="fixed w-full p-4 bottom-0 text-center border-t border-gray-200">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span>Next.JS</span>
        </a>
      </footer>
    </>
  )
}
